path_to_data: './data/datasets-promise12'
path_to_save: './result' 

N: 50
N_test: 30

img_width: 128
img_height: 128
img_thickness: 32
img_channels: 1

learning_rate: 7.5e-4
epochs: 150
val_size: 0.2
dropout: 0.5
batch_size: 128
patience: 150

f: [0, 32, 64, 128, 256, 512, 256, 128, 64, 32]
